"""Addendum: what happens on a chaotic ATTRACTOR?

Every world in run_lab.py is conservative - no friction, energy exactly conserved. Liouville
forbids attractors there: the cloud can stretch and fold but nothing pulls it onto a smaller
set. So the lab said nothing at all about strange attractors, which is a fair thing to ask.

Two dissipative worlds, same two instruments (the swing, the spread):

  lorenz  - an autonomous strange attractor. No outside clock. Any oscillation in the
            distribution has to be generated by the dynamics itself.
  driven  - a damped pendulum kicked by a perfect periodic drive, in its chaotic regime.
            Chaos plus an outside clock: the weather case (summer/winter on top of chaos).

The energy control does not apply here - these systems dissipate on purpose. The controls
that do apply: the zero-doubt run must give exactly zero bits, and the answer must not move
when the time step is halved.
"""

import json

import numpy as np

import engine as E

# ---------------------------------------------------------------------------- the worlds

SIGMA, BETA, RHO = 10.0, 8.0 / 3.0, 28.0
DRIVE_A, DRIVE_B, DRIVE_W = 1.15, 0.5, 2.0 / 3.0


def lorenz_deriv(y):
    x, yy, z = y[:, 0], y[:, 1], y[:, 2]
    out = np.empty_like(y)
    out[:, 0] = SIGMA * (yy - x)
    out[:, 1] = x * (RHO - z) - yy
    out[:, 2] = x * yy - BETA * z
    return out


def driven_deriv(y):
    """Damped driven pendulum. The drive phase rides along as a coordinate, so the
    system is autonomous and the same integrator works unchanged."""
    th, w, ph = y[:, 0], y[:, 1], y[:, 2]
    out = np.empty_like(y)
    out[:, 0] = w
    out[:, 1] = -DRIVE_B * w - np.sin(th) + DRIVE_A * np.cos(ph)
    out[:, 2] = DRIVE_W
    return out


WORLDS = {
    "lorenz": dict(
        deriv=lorenz_deriv, seed=np.array([1.0, 1.0, 20.0]),
        settle=40.0, obs=lambda y: y[:, 0], lo=-22.0, hi=22.0,
        window=3.0, T=60.0, dt=0.002,
        label="Lorenz - a strange attractor with no outside clock"),
    "driven": dict(
        deriv=driven_deriv, seed=np.array([0.2, 0.0, 0.0]),
        settle=200.0, obs=lambda y: np.sin(y[:, 0]), lo=-1.05, hi=1.05,
        window=30.0, T=600.0, dt=0.005,
        label="driven damped pendulum - chaos riding on a periodic drive"),
}


def settle_one(w):
    """Run one trajectory onto the attractor first, so the ensemble starts where the
    long-run behaviour lives instead of on the way in."""
    y = w["seed"][None, :].copy()
    for _ in range(int(round(w["settle"] / w["dt"]))):
        y = E.rk4(w["deriv"], y, w["dt"])
    return y[0]


def run(name, m=6000, sigma=0.02, dt=None, keep_phase=True):
    w = WORLDS[name]
    dt = dt or w["dt"]
    base = settle_one(w)
    rng = np.random.default_rng(20260729)
    y = np.tile(base, (m, 1))
    if sigma > 0:
        noise = rng.normal(0.0, sigma, (m - 1, y.shape[1]))
        if keep_phase and name == "driven":
            noise[:, 2] = 0.0          # every copy shares one clock: the drive is not in doubt
        y[1:] += noise

    n = int(round(w["T"] / dt))
    stride = max(int(round(0.05 / dt)), 1)
    times, obs = [], []
    for i in range(n + 1):
        if i % stride == 0:
            times.append(i * dt)
            obs.append(w["obs"](y))
        y = E.rk4(w["deriv"], y, dt)
    return np.array(times), np.array(obs)


def measure(name, times, obs):
    w = WORLDS[name]
    mean = obs.mean(axis=1)
    env = E.envelope(mean, times, w["window"])
    ok = np.isfinite(env)
    ent = E.entropy_curve(obs, w["lo"], w["hi"], 64)
    ceil = E.entropy_ceiling(w["lo"], w["hi"], 64, 40000)
    # the tail: is the swing still there at the end, or gone?
    tail = env[ok][-len(env[ok]) // 5:]
    return {
        "label": w["label"],
        "swing_start": float(env[ok][0]),
        "swing_tail_mean": float(tail.mean()),
        "swing_ratio": float(tail.mean() / env[ok][0]),
        "coherence_time": E.coherence_time(env, times),
        "entropy_start_bits": float(ent[0]),
        "entropy_end_bits": float(ent[-1]),
        "entropy_ceiling_bits": float(ceil),
    }, mean, env, ent


def main():
    out, store = {}, {}
    for name in WORLDS:
        times, obs = run(name)
        met, mean, env, ent = measure(name, times, obs)

        # control 1: no doubt at all
        _, obs0 = run(name, m=200, sigma=0.0)
        met["control_entropy_max_bits"] = float(
            E.entropy_curve(obs0, WORLDS[name]["lo"], WORLDS[name]["hi"], 64).max())
        met["control_spread_max"] = float(obs0.std(axis=1).max())

        # control 2: halve the time step, the verdict must not move
        t2, o2 = run(name, m=1500, dt=WORLDS[name]["dt"] / 2)
        m2, *_ = measure(name, t2, o2)
        met["half_step_swing_ratio"] = m2["swing_ratio"]

        out[name] = met
        store[f"{name}_t"] = times
        store[f"{name}_mean"] = mean
        store[f"{name}_env"] = env
        store[f"{name}_S"] = ent

        print(f"{name:8s} {met['label']}")
        print(f"         swing {met['swing_start']:.4f} -> {met['swing_tail_mean']:.4f} "
              f"({met['swing_ratio']:.3f}x)   t_coh={met['coherence_time']}")
        print(f"         bits  {met['entropy_start_bits']:.2f} -> "
              f"{met['entropy_end_bits']:.2f} / {met['entropy_ceiling_bits']:.2f}")
        print(f"         controls: zero-doubt {met['control_entropy_max_bits']:.1e} bits, "
              f"spread {met['control_spread_max']:.1e}, "
              f"half-step swing {met['half_step_swing_ratio']:.3f}x")

    np.savez_compressed("attractor_curves.npz", **store)
    with open("attractor_metrics.json", "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)
    print("\nwrote attractor_metrics.json, attractor_curves.npz")


if __name__ == "__main__":
    main()
